# Generated by Django 2.2.15 on 2021-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_fname', models.CharField(max_length=255)),
                ('sent_my_file', models.FileField(upload_to='')),
            ],
        ),
    ]
